eureka:
  client:
    healthcheck:
      enabled: true

owms:
  partners:
    sps01: tcpip-palett1
    sps02: tcpip-palett2

---
spring:
  profiles: ASYNCHRONOUS

owms:
  driver:
    osip:
      enabled: true
      err:
        queue-name: tms-rtng-err
        exchange-name: osip
        routing-key-in: osip.err.ss
        routing-key-out: osip.err.mfc
      locu:
        queue-name: tms-rtng-locu
        exchange-name: osip
        routing-key-in: osip.locu.ss
      sysu:
        queue-name: tms-rtng-sysu
        exchange-name: osip
        routing-key-in: osip.sysu.ss
      req:
        queue-name: tms-rtng-req
        exchange-name: osip
        routing-key-in: osip.req.ss
      res:
        exchange-name: osip
      upd:
        queue-name: tms-rtng-upd
        exchange-name: osip
        routing-key-in: osip.upd.ss
