spring:
  application:
    name: routing-service
  cloud:
    config:
      fail-fast: true # true means retry
      discovery:
        enabled: false
        service-id: openwms-config
      enabled: false
      retry:
        max-attempts: 120
    discovery:
      enabled: false
  config:
    location: classpath:application.yml
  security:
    user:
      password: sa
      name: user
  jpa:
    show-sql: false
    open-in-view: false
  liquibase:
    enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /ui/**
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  zipkin:
    enabled: false
  rabbitmq:
    listener:
      simple:
        retry:
          max-attempts: 3
          enabled: true
          initial-interval: 1s
          max-interval: 1s

camunda:
  bpm:
    auto-deployment-enabled: true
    enabled: true
    deployment-resource-pattern: classpath*:**/camunda/processes/*.bpmn20.xml,classpath*:**/camunda/processes/*.bpmn,classpath*:**/camunda/processes/*.dmn11.xml,classpath*:**/camunda/processes/*.dmn

feign:
  httpclient:
    connection-timeout: 30000
    connection-timer-repeat: 30000
ribbon:
  connectTimeout: 30000
  ReadTimeout: 30000

owms:
  driver:
    osip:
      enabled: true
  eureka:
    url: http://user:sa@localhost:8761
    zone: ${owms.eureka.url}/eureka/
  routing:
    serialization: json
  srv:
    protocol: http
    hostname: localhost

server:
  port: ${PORT:8130}

eureka:
  client:
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 10 # default is 30
    service-url:
      defaultZone: ${owms.eureka.zone}  # Must be camelCase
  instance:
    hostname: ${owms.srv.hostname}
    secure-port-enabled: false
    non-secure-port-enabled: true
    metadata-map:
      username: ${spring.security.user.name}
      password: ${spring.security.user.password}
      protocol: ${owms.srv.protocol}
      zone: ${owms.eureka.zone}
      config-protocol: http # The protocol used to access the config server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    rabbit:
      enabled: false
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
  info:
    git:
      mode: full

logging:
  file:
    name: BOOT-TMS-Routing.log
    path: "/tmp/owms"

flowable:
  app:
    enabled: false
    deploy-resources: false
    servlet:
      load-on-startup: 0
  cmmn:
    enabled: false
    deploy-resources: false
    servlet:
      load-on-startup: 0
    async:
      executor:
        auto-activate: false
  content:
    enabled: false
    servlet:
      load-on-startup: 0
  database-schema-update: false
  dmn:
    enabled: false
    deploy-resources: false
    resource-location: classpath*:/flowable/dmn/
    servlet:
      load-on-startup: 0
    history-enabled: false
  form:
    enabled: false
    deploy-resources: false
    servlet:
      load-on-startup: 0
  idm:
    enabled: false
    servlet:
      load-on-startup: 0
  process-definition-location-prefix: classpath*:/flowable/processes/
  process:
    enabled: false
    servlet:
      load-on-startup: 0
    async-history:
      executor:
        auto-activate: false
  jpa-enabled: false
  async-executor-activate: false


---
spring:
  config:
    activate:
      on-profile: ASYNCHRONOUS

management:
  health:
    rabbit:
      enabled: true

owms:
  driver:
    osip:
      err:
        queue-name: tms-rtng-err
        exchange-name: osip
        routing-key-in: osip.err.ss
      locu:
        queue-name: tms-rtng-locu
        exchange-name: osip
        routing-key-in: osip.locu.ss
      sysu:
        queue-name: tms-rtng-sysu
        exchange-name: osip
        routing-key-in: osip.sysu.ss
      req:
        queue-name: tms-rtng-req
        exchange-name: osip
        routing-key-in: osip.req.ss
      res:
        exchange-name: osip
      upd:
        queue-name: tms-rtng-upd
        exchange-name: osip
        routing-key-in: osip.upd.ss
      updx:
        queue-name: tms-rtng-updx
        exchange-name: osip
        routing-key-in: osip.updx.ss
  events:
    common:
      lg:
        exchange-name: common.lg
        queue-name: routing-lg-queue
        routing-key: lg.event.*
      loc:
        exchange-name: common.lg
        queue-name: routing-loc-queue
        routing-key: loc.event.*
  partners:
    sps01: osip.res.1
    sps02: osip.res.2
    sps03: osip.res.3
    sps04: osip.res.4
    sps05: osip.res.5
  requests:
    routing:
      to:
        exchange-name: tms.requests
        queue-name: routing-requests-queue
        routing-key: "*.*.*"
  routing:
    serialization: json
    dead-letter:
      exchange-name: dle.routing
      queue-name: dlq-routing-queue

health:
  config:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: "!ASYNCHRONOUS"

owms:
  partners:
    sps01: SPS01
    sps02: SPS02
    sps03: SPS03
    sps04: SPS04
    sps05: SPS05

---
spring:
  config:
    activate:
      on-profile: DEMO
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: DISTRIBUTED
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
    discovery:
      enabled: true
  zipkin:
    sender:
      type: web
    enabled: true

---
spring:
  config:
    activate:
      on-profile: FLOWABLE
flowable:
  app:
    enabled: true
    deploy-resources: true
    servlet:
      load-on-startup: 1
  cmmn:
    enabled: true
    deploy-resources: true
    servlet:
      load-on-startup: 1
    async:
      executor:
        auto-activate: true
  content:
    enabled: true
    servlet:
      load-on-startup: 1
  database-schema-update: true
  dmn:
    enabled: true
    deploy-resources: true
    servlet:
      load-on-startup: 1
    history-enabled: true
  form:
    enabled: true
    deploy-resources: true
    servlet:
      load-on-startup: 1
  idm:
    enabled: true
    servlet:
      load-on-startup: 1
  process:
    enabled: true
    servlet:
      load-on-startup: 1
    async-history:
      executor:
        auto-activate: true
  jpa-enabled: true
  async-executor-activate: true

camunda:
  bpm:
    auto-deployment-enabled: false
    enabled: false

---
spring:
  config:
    activate:
      on-profile: HEROKU
  main:
    banner-mode: "OFF"
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
      headers:
        protocol: ${owms.cfgsrv.protocol:https}
    discovery:
      enabled: true

owms:
  srv:
    protocol: https
    hostname: openwms-routing-service.herokuapp.com

eureka:
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    statusPageUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/info
    healthCheckUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/health
    homePageUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/
    metadata-map:
      config-protocol: ${owms.cfgsrv.protocol:https}

---
spring:
  config:
    activate:
      on-profile: SYNCHRONOUS
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true
    discovery:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: TEST
  cloud:
    config:
      fail-fast: false
  main:
    banner-mode: "off"

---
spring:
  config:
    activate:
      on-profile: TESTPG
  jpa:
    database: postgresql
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.default_schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:testdb
    username: KARL
    password: KARL
